#define MAXTABLAFONDOPENSIONES 2
#define MAXTABLAESTADOCIVIL 4
#define MAXTABLAGRADOINSTRUCCION 3

#define MAXTABLAGRUPOOCUPACIONAL 4
#define MAXTABLADIRECTORSUPERIOR 2
#define MAXTABLAEJECUTIVO 3
#define MAXTABLAESPECIALISTA 10
#define MAXTABLAAPOYO 12

#define MAXTABLAHORARIO 2
#define MAXTABLATIPOTRABAJADOR 2
#define MAXTABLAPROVINCIA 3
#define MAXTABLABANCO 3
#define MAXTABLAMES 12

#define MAXDNI 9
#define MAXRUC 12
#define MAXTELEFONO 10
#define MAXCODIGO 9
#define MAXNROCUENTA 17
#define MAXCCI 21
#define MAXSEXO 2
#define MAXCLASEDECARGO 27
#define SUELDOMINIMO 930
#define MAXSUELDOBASE 4000
#define MAXOPCIONES 14

#define MAX 100
#define LIM 50
#define DELTA 20
